### ISSUE TITLE
Webpack integration

### ISSUE THREAD

**Issue by brenwell** [osartun/Backbone.Undo.js#14]
Hey there nice library. I was hoping to try it out after checking out your video.

However I am using webpack to require dependencies, and I am having a hard time getting Backbone.Undo to find underscore & backbone.

May there is something really obvious, any hep would be grand

```coffeescript

$ = require 'jquery'
_ = require 'underscore'
Backbone = require 'backbone'
BaseView = require 'baseView'
Undo = require 'undo'


class AdminPage extends BaseView

  name: "AdminPage"
  id: "admin-page"
  autoDestroy: true
  template: require '../../../jade/page/admin'
  css: require '../../../less/page/admin'

  #----------------------

  events:
    "keyup[esc]":            "undo"

  #----------------------

  undo: ->
    alert "undo"

module.exports = AdminPage
```

Thanks in advance

**Comment by darrrk** [comment]
Close this, should work with 0.2.5

**Comment by osartun** [comment]
Great to know!
I never worked with webpack and didn't get to deal with this issue
