### ISSUE TITLE
Undo manager is not compatible with 1.3.x backbone version 

### ISSUE THREAD

**Issue by vorotina** [osartun/Backbone.Undo.js#21]

**Comment by osartun** [comment]
Thank you for creating this issue. However, could you be any more specific about what exactly doesn't work with Backbone 1.3.x versions? I just ran the tests with the latest stable versions of Underscore and Backbone (1.8.3 & 1.3.3) and all tests have passed, so I don't see an incompatibility there.

**Comment by vorotina** [comment]
@osartun No issues found. I just saw restriction in package.json
  "dependencies": {
    "backbone": "1.0.0 - 1.2.1",
    "underscore": "1.4.4 - 1.8.3"
  }

**Comment by osartun** [comment]
Ah, oh, ok! Good to know! I'm gonna change that

**Comment by osartun** [comment]
I changed the version specification in the dependencies, I guess this should fix it. Also allowed any upcoming versions.
