### ISSUE TITLE
For Version v0.5.3

### ISSUE THREAD

**Issue by niyazhussain** [osartun/Backbone.Undo.js#25]
My app is developed in old version of backbone (v0.5.3), any idea if it succeds if i try to rewrite this for older version.

**Comment by osartun** [comment]
I'm sorry, I don't know how much older versions differ from the supported ones, so I can't make any valuable assertion about that.

**Comment by niyazhussain** [comment]
thanks for you reply , anyway i will try for that one if it suceeds i will give you the code you can post in here .
