### ISSUE TITLE
bump version for backbone 1.3.x update

### ISSUE THREAD

**Issue by codynguyen** [osartun/Backbone.Undo.js#28]
Hi,

I can see https://github.com/osartun/Backbone.Undo.js/commit/c10e9977d22ecea1fabe894be650c78ac548911f changed the backbone dependency to allow `>=1.0.0` instead of `1.0.0 - 1.2.1`. Can you bump the version to 0.2.6 and create a new release so it can be installed without having to specify the commit in bower.json file?

Thanks a lot!

**Comment by osartun** [comment]
Unfortunately I'm not entirely familiar with versioning and releases on Github. I did this https://github.com/osartun/Backbone.Undo.js/commit/9817afb2e37ca59d01b55b14dd43c42c49db7757 and that: https://github.com/osartun/Backbone.Undo.js/releases/tag/v0.2.6
I hope this was correct?
